---
grafana_public_domain: mythologic.fr
grafana_custom_configs:
  - src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

grafana_data_dir: /var/lib/grafana
grafana_log_dir: /var/log/grafana

grafana_admin_user: admin

grafana_filesystem_list:
  - lv: lv_grafana_data
    vg: "{{ custom_vg_name }}"
    size: 1G
    path: "{{ grafana_data_dir }}"
    owner: "{{ grafana_owner }}"
    group: "{{ grafana_owner }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false
  - lv: lv_grafana_log
    vg: "{{ custom_vg_name }}"
    size: 500M
    path: "{{ grafana_log_dir }}"
    owner: "{{ grafana_owner }}"
    group: "{{ grafana_owner }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

grafana_custom_packages:
  - nss
  - gtk3

grafana_http_port: 3000

grafana_system_directories:
  - path: /etc/grafana
  - path: /usr/share/grafana
  - path: "{{ grafana_data_dir }}"
  - path: /var/run/grafana

grafana_owner: grafana
grafana_group: grafana

ssl_minimal_file:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
    dest: /etc/grafana/cert.pem
    user: "{{ grafana_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    dest: /etc/grafana/chain.pem
    user: "{{ grafana_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: /etc/grafana/fullchain.pem
    user: "{{ grafana_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: /etc/grafana/privkey.pem
    user: "{{ grafana_owner }}"
