---
- name: Import elastic gpg key
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ filebeat_gpg_key }}"

- name: Add repo for elk
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.apt_repository:
    repo: "deb {{ item }}"
    state: present
  loop: "{{ filebeat_deb }}"
