---
- name: Create directory
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(filebeat_owner) }}"
    group: "{{ item.group | default(filebeat_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ filebeat_custom_dirs }} "

- ansible.builtin.import_tasks: gpg.yml

- name: Install binaries
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.package:
    name: "filebeat{{ filebeat_version }}"
    state: "{{ filebeat_install_mode }}"
  notify:
    - filebeat_need_restart

- name: Template config file
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(filebeat_owner) }}"
    group: "{{ item.group | default(filebeat_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ filebeat_custom_templates }}"
  notify:
    - filebeat_need_restart

- name: Template input file
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ filebeat_input_dir }}/{{ item.src | basename }}.yml"
    owner: "{{ item.owner | default(filebeat_owner) }}"
    group: "{{ item.group | default(filebeat_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ filebeat_input_templates }}"
  notify:
    - filebeat_need_restart

- ansible.builtin.import_tasks: generic_ac.yml
  when: filebeat_use_generic_ac
