---
certbot_user: certbot
certbot_group: certbot

certbot_home: /opt/certbot
certbot_cred_path: "{{ certbot_home }}/certbot.cred"

certbot_force_renew: false
certbot_clean_previous_install: false

certbot_package:
  - certbot
  - python3-certbot-nginx
  - python3-certbot-dns-ovh
  - cron
  - acl

certbot_final_name_pattern: "{{ ansible_hostname }}"
certbot_email_contact: contact@ether-source.fr
certbot_main_domain: "{{ certbot_final_name_pattern }}.mythologic.fr"
certbot_domain_to_claim:
  - "{{ certbot_main_domain }}"


certbot_directories:
  - path: "{{ certbot_home }}"
  - path: "{{ certbot_home }}/work"
  - path: "{{ certbot_home }}/config"
  - path: "{{ certbot_home }}/log"
  - path: "{{ certbot_home }}/eden"
  - path: /etc/letsencrypt
    recurse: true

certbot_templates:
  - src: certbot.sh.j2
    dest: "{{ certbot_home }}/certbot.sh"
  - src: certbot_force.sh.j2
    dest: "{{ certbot_home }}/certbot_force.sh"
  - src: certbot.cred.j2
    dest: "{{ certbot_cred_path }}"
  - src: certbot_eden.sh.j2
    dest: /usr/bin/certbot_eden.sh
    mode: "0770"

certbot_credential_dns_ovh_endpoint: "{{ lookup('hashi_vault', hashi_certbot_path ~ '/certbot/ovh:dns_ovh_endpoint ' ~ hashi_connect) }}"
certbot_credential_dns_ovh_application_key: "{{ lookup('hashi_vault', hashi_certbot_path ~ '/certbot/ovh:dns_ovh_application_key ' ~ hashi_connect) }}"
certbot_credential_dns_ovh_application_secret: "{{ lookup('hashi_vault', hashi_certbot_path ~ '/certbot/ovh:dns_ovh_application_secret ' ~ hashi_connect) }}"
certbot_credential_dns_ovh_consumer_key: "{{ lookup('hashi_vault', hashi_certbot_path ~ '/certbot/ovh:dns_ovh_consumer_key ' ~ hashi_connect) }}"

certbot_custom_become_method: sudo