---

- name: Download Farmer binary
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.get_url:
    url: "{{ subspace_farmer_binary_url }}"
    dest: "{{ subspace_farmer_binary_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    force: true
    mode: '0750'
  notify:
    - subspace_farmer_need_restart
  when: subspace_donwload_binary

- name: Create farmer directory
  become: true
  become_method: "{{ custom_become_method }}"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(subspace_owner) }}"
    group: "{{ item.group | default(subspace_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ subspace_farmer_directories }}"

- name: Template Subspace Farmer file
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(subspace_owner) }}"
    group: "{{ item.group | default(subspace_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ subspace_farmer_templates }}"
  notify:
    - subspace_farmer_need_restart