---

- name: Install binaries for Subspace
  become: true
  become_method: "{{ subspace_custom_become_method }}"
  ansible.builtin.package:
    name: "{{ subspace_extra_package }}"
    state: present

- name: Run Node task
  ansible.builtin.import_tasks: node.yml
  when: subspace_node_install_enabled | bool

- name: Run Operator task
  ansible.builtin.import_tasks: operator.yml
  when: subspace_operator_install_enabled | bool
