---
- name: Install haproxy packages
  become: true
  become_method: "{{ haproxy_sudo_become_method }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ haproxy_packages }}"
  notify:
    - haproxy_need_restart

- name: Create directory
  become: true
  become_method: "{{ haproxy_sudo_become_method }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(haproxy_owner) }}"
    group: "{{ item.group | default(haproxy_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ haproxy_custom_dirs }} "

- name: Set nonlocal_bind to 1
  become: true
  become_method: "{{ haproxy_sudo_become_method }}"
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    state: present
    reload: True

- name: Template haproxy config
  become: true
  become_method: "{{ haproxy_sudo_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0640') }}"
    owner: "{{ item.owner | default(haproxy_owner) }}"
    group: "{{ item.group | default(haproxy_group) }}"
  loop: "{{ haproxy_templates }}"
  notify: haproxy_need_restart

- name: Source ssl file from certbot
  become: true
  become_method: "{{ haproxy_sudo_become_method }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ haproxy_owner }}"
    group: "{{ haproxy_group }}"
    state: link
  loop: "{{ haproxy_ssl_file }}"
  notify:
    - haproxy_need_restart