galaxy_info:
  author: Douceur
  description: this role simply install & configure haproxy
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [haproxy]

dependencies:
  - role: tocard.utils.user
    user_name: "{{ haproxy_owner }}"
    user_group: "{{ haproxy_group }}"
  - role: tocard.utils.filesystem
    filesystem_list: "{{ haproxy_filesystem_list }}"




