---
- name: Group creation
  become: true
  become_method: "{{ custom_become_method }}"
  group:
    name: "{{ user_group }}"
    state: present
  when: user_group is not none

- name: User creation
  become: true
  become_method: "{{ custom_become_method }}"
  user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    shell: "{{ user_shell }}"
    append: true
    groups: "{{ user_groups }}"
    expires: "{{ user_expires }}"
    password: "{{ user_password | password_hash('sha512') | default(omit) }}"
    password_expire_max: -1
  when: user_name is not none
