---
- name: Group creation
  become: true
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present
  when: user_group is not none

- name: User creation
  become: true
  ansible.builtin.user:
    name: "{{ user_name | default(omit) }}"
    group: "{{ user_group | default(omit) }}"
    shell: "{{ user_shell }}"
    append: true
    groups: "{{ user_groups | default(omit) }}"
    expires: "{{ user_expires }}"
    password: "{{ user_password | password_hash('sha512') | default(omit) }}"
    password_expire_max: -1
    system: "{{ user_system | default(omit) }}"
  when: user_name is not none
