---
- name: Group creation
  become: true
  become_method: "{{ user_become_method }}"
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present
  when: user_group is not none

- name: User creation
  become: true
  become_method: "{{ user_become_method }}"
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    shell: "{{ user_shell }}"
    append: true
    groups: "{{ user_groups }}"
    expires: "{{ user_expires }}"
    password: "{{ user_password | password_hash('sha512') | default(omit) }}"
    password_expire_max: -1
    system: "{{ user_system }}" 
  when: user_name is not none
