galaxy_info:
  author: Douceur
  description: this role simply install & configure vault server
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22

  galaxy_tags: ['vault']

dependencies:
  - role: tocard.utils.user
    user_name: "{{ vault_user }}"
    user_group: "{{ vault_group }}"
    user_groups: "{{ vault_groups }}"
  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ vault_filesystem_lvs_mounts }}"
  - role: tocard.utils.certbot
    when: vault_ssl_enabled | bool
    tags:
      - vault
