---
- name: Restart Subspace Node
  become: true
  ansible.builtin.systemd:
    name: subspace_node
    state: restarted
    enabled: true
    daemon_reload: true
  listen: subspace_node_need_restart
