---
nats_version: v2.10.2
nats_user: nats
nats_group: nats
nats_groups: []
nats_password:
nats_config_dir: /etc/nats
nats_data_dir: /var/lib/nats
nats_log_dir: /var/log/nats
nats_bin_path: /usr/local/bin/nats-server
nats_service_name: nats
nats_port: 4222
nats_http_port: 8222


nats_temp_folder: /tmp/nats

nats_directories:
  - "{{ nats_config_dir  }}"
  - "{{ nats_data_dir }}"
  - "{{ nats_log_dir }}"
  - "{{ nats_temp_folder }}"


nats_templates:
  - src: nats.conf.j2
    dest: "{{ nats_config_dir }}/nats.conf"
  - src: nats.service.j2
    dest: "/etc/systemd/system/{{ nats_service_name }}.service"
    mode: '0644'

nats_download_url: "https://github.com/nats-io/nats-server/releases/download/{{ nats_version }}/nats-server-{{ nats_version }}-linux-amd64.tar.gz"