---
- name: Create promtail directories
  become: true
  become_method: "{{ custom_become_method }}"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(promtail_owner) }}"
    group: "{{ item.group | default(promtail_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ promtail_directories }}"

- name: Install promtail package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    name: promtail
    state: present

- name: Template promtail file
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(promtail_owner) }}"
    group: "{{ item.group | default(promtail_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ promtail_templates }}"
  notify:
    - promtail_need_restart