---

- name: Install binaries for cosmos_node
  become: true
  become_method: "{{ cosmos_node_sudo_method }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ cosmos_node_packages }}"

- name: Create directory
  become: true
  become_method: "{{ cosmos_node_sudo_method }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(cosmos_node_owner) }}"
    group: "{{ item.group | default(cosmos_node_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ cosmos_node_directories }}"

- name: Add a wrapper for shell into user .bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ cosmos_node_owner }}/.bashrc"
    line: "{{ item }}"
    create: True
  loop:
    - "alias {{ cosmos_node_short_name }}='{{ cosmos_node }}'"
    - "alias {{ cosmos_node }}='{{ cosmos_node }} --home {{ cosmos_node_path }}'"