galaxy_info:
  author: Douceur
  description: this role simply install & configure metricbeat
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['metricbeat']

dependencies:
  - name: tocard.utils.filesystem
    filesystem_list: "{{ metricbeat_filesystem_list }}"


