---
filebeat_version: ""

filebeat_user: root
filebeat_group: root

filebeat_user: filebeat
filebeat_password: changeme

filebeat_module_path: /etc/filebeat/modules.d

filebeat_custom_templates:
  - src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: "0640"

filebeat_input_templates: []

filebeat_log_dir: /var/log/filebeat
filebeat_input_dir: /etc/filebeat/inputs.d


filebeat_custom_dirs:
  - path: "{{ filebeat_log_dir }}"
    state: directory
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: "0750"
  - path: "{{ filebeat_input_dir }}"
    state: directory
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: "0750"

filebeat_filesyste_vg_name: olympus
filebeat_filesystem_lvs_mounts:
  - lv: lv_filebeat_log
    vg: "{{ filebeat_filesyste_vg_name }}"
    size: 1g
    path: "{{ filebeat_log_dir }}"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"

filebeat_install_mode: latest
filebeat_custom_become_method: sudo

filebeat_use_generic_ac: false

subspace_filebeat_enabled: false
filebeat_log_path_to_watch: []

filebeat_gpg_key:
  - https://artifacts.elastic.co/GPG-KEY-elasticsearch


filebeat_deb:
  - https://artifacts.elastic.co/packages/8.x/apt stable main

