---
- name: Restart cosmos_node
  become: true
  become_method: "{{ cosmos_node_sudo_method }}"
  ansible.builtin.systemd:
    name: "{{ cosmos_node }}"
    state: restarted
    enabled: true
    daemon_reload: true
  listen: cosmos_node_need_restart