---
haproxy_user: haproxy
haproxy_group: haproxy
haproxy_groups: [certbot]
haproxy_version: 2.8.9-1ppa1~jammy
haproxy_custom_dirs:
  - path: /run/haproxy
    mode: "0750"
  - path: /etc/haproxy/ssl
    mode: "0750"

haproxy_packages:
  - apt-utils
  - "haproxy={{ haproxy_version }}"

haproxy_templates:
  - src: haproxy.cfg.j2
    dest: /etc/haproxy/00_haproxy.cfg
    mode: "0640"
  - src: stats.cfg.j2
    dest: /etc/haproxy/stats.cfg
    mode: "0640"
  - src: https.cfg.j2
    dest: /etc/haproxy/https.cfg
    mode: "0640"
  - src: elasticsearch.cfg.j2
    dest: /etc/haproxy/elasticsearch.cfg
    mode: "0640"
  - src: haproxy.service.j2
    dest: /lib/systemd/system/haproxy.service
    mode: "0644"

haproxy_stats_user: admin
haproxy_stats_password: "{{ lookup('hashi_vault', hashi_haproxy_path ~ '/stats_user:moz ' ~ hashi_connect) }}"

haproxy_config_folder: /etc/haproxy

haproxy_filesystem_vg_name: olympus
haproxy_filesystem_lvs_mounts:
  - lv: lv_haproxy_log
    vg: "{{ haproxy_filesystem_vg_name }}"
    size: 1g
    path: /var/log/haproxy
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"

haproxy_certs_path: /etc/haproxy/ssl

haproxy_ssl_file:
  - src: "/opt/certbot/eden/cert.pem"
    dest: "{{ haproxy_certs_path }}/cert.pem"
  - src: "/opt/certbot/eden/chain.pem"
    dest: "{{ haproxy_certs_path }}/chain.pem"
  - src: "/opt/certbot/eden/fullchain.pem"
    dest: "{{ haproxy_certs_path }}/fullchain.pem"
  - src: "/opt/certbot/eden/fullchain.pem.key"
    dest: "{{ haproxy_certs_path }}/fullchain.pem.key"

haproxy_sudo_become_method: sudo
