---

subspace_node_install_enabled: true

subspace_node_install_path: "{{ subspace_install_path }}/node"
subspace_node_binary_url: "{{ subspace_github_url }}/{{ subspace_snapshot }}/subspace-node-{{ subspace_binary }}-{{ subspace_snapshot}}"
subspace_node_binary_path: "/usr/bin/{{ subspace_node_binary_name}}"
subspace_node_binary_name: subspace_node
subspace_node_logrotate_file: subspace_node
subspace_node_templates:
  - src: subspace_node.service.j2
    dest: /etc/systemd/system/subspace_node.service
    mode: "0640"
  - src: subspace_node.j2
    dest: "{{ subspace_logrotate_folder }}/{{ subspace_node_logrotate_file }}"
subspace_node_log_file: node.log
subspace_node_log_folder: /var/log/chimera/subspace_node
subspace_node_directories:
  - path: "{{ subspace_node_install_path }}"
  - path: "{{ subspace_node_log_folder }}"

subspace_node_filesystem_enabled: true

subspace_node_filesystem_disk_mounts:
  - disk: sdb
    path: "{{ subspace_node_install_path }}"
    owner: "{{ subspace_user }}"
    group: "{{ subspace_group }}"

subspace_node_filesystem_lvs_mounts:
  - lv: lv_subspace_node_log
    vg: "{{ suspace_custom_vg_name }}"
    size: 2g
    path: "{{ subspace_node_log_folder }}"
    owner: "{{ subspace_user }}"
    group: "{{ subspace_group }}"


subspace_node_prometheus_port: 9615

subspace_node_p2p_port: 30333
subspace_node_dsn_port: 30433
