---

subspace_operator_install_enabled: true
subspace_operator_install_path: "{{ subspace_install_path }}/node"
subspace_operator_binary_url: "{{ subspace_github_url }}/{{ subspace_snapshot }}/subspace-node-{{ subspace_binary }}-{{ subspace_snapshot}}"
subspace_operator_binary_path: "/usr/bin/{{ subspace_operator_binary_name}}"
subspace_operator_binary_name: subspace_operator
subspace_operator_logrotate_file: subspace_operator
subspace_operator_templates:
  - src: subspace_operator.service.j2
    dest: /etc/systemd/system/subspace_operator.service
    mode: "0640"
  - src: subspace_operator.j2
    dest: "{{ subspace_logrotate_folder }}/{{ subspace_operator_logrotate_file }}"
subspace_operator_log_file: operator.log
subspace_operator_log_folder: /var/log/chimera/subspace_operator
subspace_operator_directories:
  - path: "{{ subspace_operator_install_path }}"
  - path: "{{ subspace_operator_log_folder }}"

subspace_operator_filesystem_enabled: true
subspace_operator_filesystem_lvs_mounts:
  - lv: lv_chimera
    vg: "{{ suspace_custom_vg_name }}"
    size: 10g
    path: "{{ subspace_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"

  - lv: lv_subspace_operator_log
    vg: "{{ suspace_custom_vg_name }}"
    size: 2g
    path: "{{ subspace_operator_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"


subspace_operator_prometheus_port: 9615
subspace_operator_p2p_port: 30333
subspace_operator_dsn_port: 30433
