---

- name: Source ssl file from certbot
  become: true
  become_method: "{{ kibana_become_metthod }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ kibana_owner }}"
    group: "{{ kibana_group }}"
    state: link
  loop: "{{ kibana_ssl_file }}"
  notify:
    - kibana_need_restart