---

- name: Source ssl file from certbot
  become: true
  become_method: "{{ kibana_custom_become_method }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    state: link
    follow: False
  loop: "{{ kibana_ssl_file }}"
  notify:
    - kibana_need_restart