---

- name: Extend or format the fs for whole disk
  become: true
  community.general.filesystem:
    fstype: "{{ item.fstype | default('xfs') }}"
    dev: "/dev/{{ item.disk }}"
    resizefs: "{{ item.resizefs | default('true') }}"
  register: _filesystem_changed

- name: Mount disk
  become: true
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "/dev/{{ item.disk }}"
    fstype: "{{ item.fstype | default('xfs') }}"
    opts: "{{ item.opts | default(omit) }}"
    state: present
  register: _filesystem_fstab_changed

- ansible.builtin.import_tasks: mount.yml