---

- name: Create mountpoint folder
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(filesystem_mountpoint_user) }}"
    group: "{{ item.group | default(filesystem_mountpoint_group) }}"
    mode: "{{ item.mode | default(filesystem_mountpoint_mode) }}"
    state: directory
  loop: "{{ filesystem_mounts }}"

- name: Process lvs filesystem
  ansible.builtin.include_tasks: lvs.yml
  loop: "{{ filesystem_lvs_mounts }}"

- name: Process disk filesystem
  ansible.builtin.include_tasks: disk.yml
  loop: "{{ filesystem_disk_mounts }}"

- name: Process nfs filesystem
  ansible.builtin.include_tasks: nfs.yml
  loop: "{{ filesystem_nfs_mounts }}"

- name: Ensure right are correctly set
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(filesystem_mountpoint_user) }}"
    group: "{{ item.group | default(filesystem_mountpoint_group)  }}"
    mode: "{{ item.mode | default(filesystem_mountpoint_mode) }}"
    state: directory
  loop: "{{ filesystem_mounts }}"
