---

- name: Create filesystem directory before mount
  become: true
  become_method: "{{ filesystem_custom_become_method }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ filesystem_list }}"

- ansible.builtin.import_tasks: disk.yml

- ansible.builtin.import_tasks: lvm.yml

