galaxy_info:
  author: Douceur
  description: this role configure artifactory
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [artifactory]

dependencies:
  - name: tocard.utils.user
    user_name: "{{ artifactory_owner }}"
    user_group: "{{ artifactory_group }}"

