---

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ nats_config_dir }}  "
    state: directory
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: '0750'
  loop: "{{ nats_directories }}"

- name: Extract NATS server tarball
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/nats-io/nats-server/releases/download/{{ nats_version }}/nats-server-{{ nats_version }}-linux-amd64.tar.gz"
    dest: /tmp/nats
    creates: true
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    remote_src: true

- name: copy binary
  become: true
  ansible.builtin.copy:
    src: /tmp/nats/nats-server
    dest: "{{ nats_bin_path }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "0700"

- name: Create NATS configuration file
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "{{ item.mode | default('0640') }}"
  notify: restart nats
  loop: "{{ nats_templates }}"
