---

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "0750"
  loop: "{{ nats_directories }}"

- name: Donwload & extract NATS
  become: true
  ansible.builtin.unarchive:
    src: "{{ nats_download_url }}"
    dest: "{{ nats_temp_folder }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    remote_src: true
    mode: "0750"
  notify: restart nats

- name: copy binary
  become: true
  ansible.builtin.copy:
    src: "{{ nats_temp_folder }}/nats-server-{{ nats_version }}-linux-amd64/nats-server"
    dest: "{{ nats_bin_path }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    remote_src: true
    mode: "0700"
  notify: restart nats

- name: Create NATS configuration file
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "{{ item.mode | default('0640') }}"
  notify: restart nats
  loop: "{{ nats_templates }}"
