---

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ nats_config_dir }}"
    state: directory
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "0750"
  loop: "{{ nats_directories }}"

- name: Extract NATS server tarball
  become: true
  ansible.builtin.unarchive:
    src: 
    dest: /tmp/nats
    creates: true

- name: Donwload & extract NATS
  become: true
  ansible.builtin.unarchive:
    src: "{{ nats_download_url }}"
    dest: "{{ nats_temp_folder }}"
    owner: "{{ item.owner | default(nats_user) }}"
    group: "{{ item.group | default(nats_group) }}"
    remote_src: true
    mode: "0750"
  notify: nexus_need_restart

- name: copy binary
  become: true
  ansible.builtin.copy:
    src: "{{ nats_temp_folder}}/nats-server"
    dest: "{{ nats_bin_path }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "0700"

- name: Create NATS configuration file
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "{{ item.mode | default("0640") }}"
  notify: restart nats
  loop: "{{ nats_templates }}"
