---

- name: Install required package
  become: true
  become_method: "{{ nexus_custom_become_method }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nexus_package}}"

- name: Create nexus directories
  become: true
  become_method: "{{ nexus_custom_become_method }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(nexus_owner) }}"
    group: "{{ item.group | default(nexus_group) }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
    recurse: "{{ item.recurse | default(omit) }}"
  loop: "{{ nexus_directories }}"

- name: Donwload & extract nexus
  become: true
  become_method: "{{ nexus_custom_become_method }}"
  ansible.builtin.unarchive:
    src: "{{ nexus_download_url }}"
    dest: "{{ nexus_home }}"
    owner: "{{ item.owner | default(nexus_owner) }}"
    group: "{{ item.group | default(nexus_group) }}"
    remote_src: true
    mode: "0750"

- name: Template nexus files
  become: true
  become_method: "{{ nexus_custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(nexus_owner) }}"
    group: "{{ item.group | default(nexus_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ nexus_templates }}"

