---
- name: Restart filebeat
  become: true
  become_method: "{{ filebeat_custom_become_method }}"
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true
    daemon_reload: true
  listen: filebeat_need_restart
