galaxy_info:
  author: Douceur
  description: this role simply install & configure elasticsearch
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [elasticsearch]

dependencies:
  - role: tocard.utils.user
    user_name: "{{ elasticsearch_user }}"
    user_group: "{{ elasticsearch_group }}"
    user_groups: "{{ elasticsearch_groups }}"

  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ elasticsearch_filesystem_lvs_mounts }}"
    filesystem_disk_mounts: "{{ elasticsearch_filesystem_disk_mounts }}"



