galaxy_info:
  author: Douceur
  description: this role simply install & configure grafana
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['grafana']

dependencies:
  - name: tocard.utils.user
    user_name: "{{ grafana_owner }}"
    user_group: "{{ grafana_group }}"
  - name: tocard.utils.filesystem
    filesystem_list: "{{ grafana_filesystem_list }}"



