galaxy_info:
  author: Douceur
  description: this role simply install & configure kibana
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [kibana]

dependencies:
  - role: tocard.utils.user
    user_name: "{{ kibana_user }}"
    user_group: "{{ kibana_group }}"
    user_groups: "{{ kibana_groups }}"

  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ kibana_filesystem_lvs_mounts }}"




