galaxy_info:
  author: Douceur
  description: this role simply create filesystem on linux
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['filesystem']

dependencies: []

