galaxy_info:
  author: Douceur
  description: this role simply install & configure subspace node & farmer
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
   - name: Fedora
     versions:
      - 37
      - 38
   - name: Ubuntu
     versions:
     - 22
     - 23
   - name: Proxmox
     versions:
     - 7
     - 8
  
  galaxy_tags: ['subspace']

dependencies:
  - name: tocard.utils.user
    user_name: "{{ subspace_owner }}"
    user_group: "{{ subspace_group }}"

  - name: tocard.utils.filesystem
    filesystem_list: "{{ subspace_node_filesystem_list }}"
    when: subspace_node_filesystem_enabled

  - name: tocard.utils.filesystem
    filesystem_list: "{{ subspace_operator_filesystem_list }}"
    when: subspace_operator_filesystem_enabled

  - name: tocard.utils.filesystem
    filesystem_list: "{{ subspace_farmer_filesystem_list }}"
    when: subspace_farmer_filesystem_enabled

