galaxy_info:
  author: Douceur
  description: this role simply install & configure subspace node & farmer
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['subspace']

dependencies:
  - name: tocard.utils.user
    user_name: "{{ subsoace_user }}"
    user_group: "{{ subspace_group }}"
    tags: ['user']

  - name: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_node_filesystem_lvs_mounts }}"
    when: subspace_node_filesystem_enabled and subspace_node_install_enabled
    tags: ['filesystem']

  - name: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_operator_filesystem_lvs_mounts }}"
    when: subspace_operator_filesystem_enabled and subspace_operator_install_enabled
    tags: ['filesystem']

  - name: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_farmer_filesystem_lvs_mounts }}"
    when: subspace_farmer_filesystem_enabled and subspace_farmer_install_enabled
    tags: ['filesystem']
