galaxy_info:
  author: Douceur
  description: this role simply install & configure subspace node & farmer
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - role: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['subspace']

dependencies:
  - role: tocard.utils.user
    user_name: "{{ subspace_user }}"
    user_group: "{{ subspace_group }}"
    tags: [user]

  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_node_filesystem_lvs_mounts }}"
    filesystem_disk_mounts: "{{ subspace_node_filesystem_disk_mounts }}"
    when: subspace_node_filesystem_enabled and subspace_node_install_enabled
    tags: [filesystem]

  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_operator_filesystem_lvs_mounts }}"
    when: subspace_operator_filesystem_enabled and subspace_operator_install_enabled
    tags: [filesystem]

