galaxy_info:
  author: Douceur
  description: this role simply install & configure subspace plotter
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - role: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [subspace, subspace_plotter]

dependencies:
  - role: tocard.utils.user
    user_name: "{{ subspace_plotter_user }}"
    user_group: "{{ subspace_plotter_group }}"
    tags: [user]

  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_plotter_filesystem_lvs_mounts }}"
    when: subspace_plotter_filesystem_enabled | bool
    tags: [filesystem]
