galaxy_info:
  author: Douceur
  description: this role configure nexus
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [nexus]

dependencies:
  - name: tocard.utils.user
    user_name: "{{ nexus_owner }}"
    user_group: "{{ nexus_group }}"

  - name: tocard.utils.filesystem
    filesystem_list: "{{ nexus_filesystem_list }}"
    tags: [filesystem]

  - role: tocard.utils.certbot
    when: nexus_ssl_enabled | bool
