---
- name: Restart kibana
  become: true
  become_method: "{{ kibana_custom_become_method }}"
  ansible.builtin.systemd:
    name: kibana
    state: restarted
    enabled: true
    daemon_reload: true
  listen: kibana_need_restart
