---

- ansible.builtin.import_tasks: debian.yml
  when: "'debian' in ansible_os_family"

- ansible.builtin.import_tasks: centos.yml
  when: "'redhat' in ansible_os_family"

- name: Install Vault package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ vault_package_list }}"

- name: Copy ssl files
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "{{ item.mode | default('0640') }}"
    remote_src: true
  loop: "{{ ssl_minimal_file }}"
  when: vault_ssl_enabled

- name: Template config files
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(vault_user) }}"
    group: "{{ item.group | default(vault_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ vault_custom_templates }}"
  notify:
    - vault_need_restart

