---

- name: Import Vault gpg key
  become: true
  become_method: "{{ vault_custom_become_method }}"
  ansible.builtin.apt_key:
    url: "{{ vault_gpg_key }}"
    state: present

- name: Add Vault repository
  become: true
  become_method: "{{ vault_custom_become_method }}"
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present

- name: Install Vault package
  become: true
  become_method: "{{ vault_custom_become_method }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ vault_package_list }}"

- name: Create link fot ssl
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    state: link

- name: Copy ssl files
  become: true
  become_method: "{{ vault_custom_become_method }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_user }}"
    state: link
  loop: "{{ vault_ssl_file }}"
  when: vault_ssl_enabled | bool

- name: Template config files
  become: true
  become_method: "{{ vault_custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(vault_user) }}"
    group: "{{ item.group | default(vault_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ vault_custom_templates }}"
  notify:
    - vault_need_restart

