---

subspace_node_user: subspace_node
subspace_node_group: subspace_node

subspace_node_donwload_binary: true

subspace_node_github_url: https://github.com/subspace/subspace/releases/download
subspace_node_chain_id: gemini-3h
subspace_node_snapshot: "{{ subspace_node_chain_id }}-2024-jul-05"


subspace_node_binary: ubuntu-x86_64-skylake
# subspace_binary: subspace-farmer-ubuntu-x86_64-v2

subspace_node_logrotate_folder: /etc/logrotate.d

subspace_node_extra_package:
  - logrotate

suspace_custom_vg_name: olympus

subspace_node_install_path: /opt/subspace_node
subspace_node_binary_url: "{{ subspace_node_github_url }}/{{ subspace_node_snapshot }}/subspace-node-{{ subspace_node_binary }}-{{ subspace_node_snapshot }}"
subspace_node_binary_path: "/usr/bin/{{ subspace_node_binary_name }}"
subspace_node_binary_name: subspace_node
subspace_node_logrotate_file: subspace_node
subspace_node_templates:
  - src: subspace_node.service.j2
    dest: /etc/systemd/system/subspace_node.service
    mode: "0640"
  - src: subspace_node.j2
    dest: "{{ subspace_node_logrotate_folder }}/{{ subspace_node_logrotate_file }}"
subspace_node_log_file: node.log
subspace_node_log_folder: /var/log/subspace_node
subspace_node_directories:
  - path: "{{ subspace_node_install_path }}"
  - path: "{{ subspace_node_log_folder }}"

subspace_node_filesystem_enabled: true

subspace_node_filesystem_disk_mounts:
  - disk: sdb
    path: "{{ subspace_node_install_path }}"
    owner: "{{ subspace_node_user }}"
    group: "{{ subspace_node_group }}"

subspace_node_filesystem_lvs_mounts:
  - lv: lv_subspace_node_log
    vg: "{{ suspace_custom_vg_name }}"
    size: 2g
    path: "{{ subspace_node_log_folder }}"
    owner: "{{ subspace_node_user }}"
    group: "{{ subspace_node_group }}"


subspace_node_prometheus_port: 9615

subspace_node_p2p_port: 30333
subspace_node_dsn_port: 30433
