---

- name: Template cosmos monitoring template
  become: true
  become_method: "{{ metricbeat_custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(metricbeat_owner) }}"
    group: "{{ item.group | default(metricbeat_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ metricbeat_cosmos_template }}"
  notify:
    - metricbeat_need_restart