---

- name: Copy default ac to hosts
  become: true
  become_method: "{{ metricbeat_custom_become_method }}"
  ansible.builtin.copy:
    src: chain.pem
    dest: /etc/metricbeat/chain.pem
    owner: root
    group: root
    mode: '0644'