---
nfs_server_user: nfs_server
nfs_server_group: nfs_server
nfs_server_groups: []

nfs_server_custom_dirs:
  - path: /run/nfs_server
    mode: "0750"
  - path: /etc/nfs_server/ssl
    mode: "0750"

nfs_server_packages:
  - nfs-kernel-server
  - rsync

nfs_server_exports:
  - path: "/mnt/sdb"
    disk: sdb
    clients: "192.168.1.0/24(rw,sync,no_root_squash)"
    options: "async,no_subtree_check"
  - path: "/mnt/sdc"
    disk: sdc
    clients: "192.168.1.0/24(rw,sync,no_root_squash)"
    options: "async,no_subtree_check"
  - path: "/mnt/sdd"
    disk: sdd
    clients: "192.168.1.0/24(rw,sync,no_root_squash)"
    options: "async,no_subtree_check"
  - path: "/mnt/sde"
    disk: sde
    clients: "192.168.1.0/24(rw,sync,no_root_squash)"
    options: "async,no_subtree_check"
  - path: "/mnt/sdf"
    disk: sdf
    clients: "192.168.1.0/24(rw,sync,no_root_squash)"
    options: "async,no_subtree_check"
  - path: "/mnt/sdg"
    disk: sdg
    clients: "192.168.1.0/24(rw,sync,no_root_squash)"
    options: "async,no_subtree_check"


nfs_server_templates:
  - src: exports.j2
    dest: /etc/exports
    mode: "0644"

