galaxy_info:
  author: Douceur
  description: this role simply install & configure filebeat
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['filebeat']

dependencies:
  - name: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ filebeat_filesystem_lvs_mounts }}"


