---

- name: Import prometheus gpg key
  become: true
  become_method: "{{ prometheus_custom_become_method }}"
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ prometheus_gpg_key }}"

- name: Add prometheus repo
  become: true
  become_method: "{{ prometheus_custom_become_method }}"
  ansible.builtin.apt_repository:
    repo: "deb {{ item }}"
    state: present
  loop: "{{ prometheus_deb }}"

- name: Create node directory
  become: true
  become_method: "{{ prometheus_custom_become_method }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(prometheus_owner) }}"
    group: "{{ item.group | default(prometheus_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ prometheus_directories }}"

- name: Download Prometheus binary
  become: true
  become_method: "{{ prometheus_custom_become_method }}"
  ansible.builtin.unarchive:
    src: "{{ prometheus_github_url }}"
    dest: "{{ prometheus_binary_path }}"
    remote_src: true
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: "0750"
  notify:
    - prometheus_need_restart

- name: Template prometheus file
  become: true
  become_method: "{{ prometheus_custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(prometheus_owner) }}"
    group: "{{ item.group | default(prometheus_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ prometheus_templates }}"
  notify:
    - prometheus_need_restart
