galaxy_info:
  author: Douceur
  description: this role configure certbot on server and create script to auto renew cert
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22
  
  galaxy_tags: ['certbot', 'ssl']

dependencies:
  - name: tocard.utils.user
    user_name: "{{ certbot_owner }}"
    user_group: "{{ certbot_group }}"

