galaxy_info:
  author: Douceur
  description: this role configure certbot on server and create script to auto renew cert
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
   - name: Fedora
     versions:
      - 37
      - 38
   - name: Ubuntu
     versions:
     - 22
     - 23
   - name: Proxmox
     versions:
     - 7
     - 8
  
  galaxy_tags: ['certbot', 'ssl']

dependencies: []

