---
metricbeat_version: ""

metricbeat_owner: root
metricbeat_group: root

metricbeat_user: metricbeat
metricbeat_password: changeme

metricbeat_module_path: /etc/metricbeat/modules.d

metricbeat_custom_templates:
  - src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0640"
  - src: system.yml.j2
    dest: "{{ metricbeat_module_path }}/system.yml"
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0640"

metricbeat_xpack_templates:
  - src: elasticsearch-xpack.yml.j2
    dest: "{{ metricbeat_module_path }}/elasticsearch-xpack.yml"
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0640"

metricbeat_centaur_templates:
  - src: centaur.yml.j2
    dest: "{{ metricbeat_module_path }}/chia.yml"
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0640"

metricbeat_hddtemp_templates:
  - src: hddtemp.yml.j2
    dest: "{{ metricbeat_module_path }}/hddtemp.yml"
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0640"

metricbeat_log_dir: /var/log/metricbeat

metricbeat_custom_dirs:
  - path: "{{ metricbeat_log_dir }}"
    state: directory
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0750"

metricbeat_filesystem_list:
  - lv: lv_metricbeat_log
    vg: "{{ custom_vg_name }}"
    size: 1g
    path: "{{ metricbeat_log_dir }}"
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

metricbeat_install_mode: latest
metricbeat_custom_become_method: sudo

metricbeat_use_generic_ac: false

metricbeat_gpg_key:
  - https://artifacts.elastic.co/GPG-KEY-elasticsearch

metricbeat_yum_repo:
  - src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

metricbeat_deb:
  - https://artifacts.elastic.co/packages/8.x/apt stable main

