---
- ansible.builtin.import_tasks: gpg.yml

- ansible.builtin.import_tasks: install.yml

- name: Force restart if needed
  ansible.builtin.meta: flush_handlers

- ansible.builtin.import_tasks: bootstrap.yml

- ansible.builtin.import_tasks: roles.yml

- ansible.builtin.import_tasks: users.yml

- name: Force restart if needed
  ansible.builtin.meta: flush_handlers

