---

- name: Source ssl file from certbot
  become: true
  become_method: "{{ elasticsearch_custom_become_method }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ elasticsearch_owner }}"
    group: "{{ elasticsearch_group }}"
    state: link
  loop: "{{ elasticsearch_ssl_file }}"
