galaxy_info:
  author: Douceur
  description: this role simply install & configure subspace cache
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - role: Ubuntu
      versions:
        - 22
  
  galaxy_tags: [subspace, subspace_cache]

dependencies:
  - role: tocard.utils.user
    user_name: "{{ subspace_cache_user }}"
    user_group: "{{ subspace_cache_group }}"
    tags: [user]

  - role: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ subspace_cache_filesystem_lvs_mounts }}"
    filesystem_disk_mounts: "{{ subspace_cache_filesystem_disk_mounts }}"
    when: subspace_cache_filesystem_enabled | bool
    tags: [filesystem]
