---
- name: Restart vault
  become: true
  become_method: "{{ custom_become_method }}"
  systemd:
    name: vault  
    state: restarted
    enabled: true
    daemon_reload: true
  listen: vault_need_restart
