---
- name: Restart StreamrNode
  become: true
  become_method: "{{ streamr_sudo_method }}"
  ansible.builtin.systemd:
    name: streamr
    state: restarted
    enabled: true
    daemon_reload: true
  listen: streamr_need_restart
