galaxy_info:
  author: Douceur
  description: this role simply install & configure ternoa node
  
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Fedora
      versions:
        - 37
        - 38
    - name: Ubuntu
      versions:
        - 22
        - 23
    - name: Proxmox
      versions:
        - 7
        - 8
  
  galaxy_tags: ['ternoa']

dependencies:
  - name: tocard.utils.user
    user_name: "{{ ternoa_owner }}"
    user_group: "{{ ternoa_group }}"
    tags: ['user']

  - name: tocard.utils.filesystem
    filesystem_list: "{{ ternoa_node_filesystem_list }}"
    when: ternoa_node_filesystem_enabled and ternoa_node_install_enabled
    tags: ['filesystem']
