---
vault_package_list:
  - "vault={{ vault_version  }}"


vault_version: 1.16.2-1
vault_bind_adress: "0.0.0.0"
vault_bind_port: 8200

vault_user: vault
vault_group: vault

vault_custom_templates:
  - src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    mode: "0640"

vault_ssl_enabled: true

vault_base_path: /opt/vault
vault_path_data: "{{ vault_base_path}}/data"

vault_filesystem_vg_name: olympus
vault_filesystem_list:
  - lv: lv_vault_data
    vg: "{{ vault_filesystem_vg_name }}"
    size: 5g
    path: "{{ vault_path_data }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

vault_ssl_file:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: "{{ vault_base_path }}/tls.crt"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: "{{ vault_base_path }}/tls.key"


vault_custom_become_method: sudo
vault_gpg_key: https://apt.releases.hashicorp.com/gpg