galaxy_info:
  author: Douceur
  description: this role install & configure generic cosmos full node

  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22

  galaxy_tags: ['blockhain', 'cosmos', 'validator', 'full-node']

dependencies: []
