galaxy_info:
  author: Douceur
  description: this role install & configure generic cosmos full node

  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 22

  galaxy_tags: [blockhain, cosmos, validator, full-node]

dependencies:
  - name: tocard.utils.user
    user_name: "{{ cosmos_node_user }}"
    user_group: "{{ cosmos_node_group }}"

  - name: tocard.utils.filesystem
    filesystem_lvs_mounts: "{{ cosmos_node_filesystem_lvs_mounts }}"
    filesystem_disk_mounts: "{{ cosmos_node_filesystem_disk_mounts }}"