---

- name: Gather facts about disks
  ansible.builtin.setup:
    filter: ansible_mounts
  register: subspace_farmer_ansible_mounts

- name: Show filtered disk info
  ansible.builtin.debug:
    var: filtered_disks
  vars:
    filtered_disks: >-
      {{
        subspace_farmer_ansible_mounts.ansible_facts.ansible_mounts
        | selectattr('device', 'in', subspace_farmer_filesystem_disk | map(attribute='disk') | list)
        | list
      }}


- name: Install os binaries requiered by Subspace controller
  become: true
  ansible.builtin.package:
    name: "{{ subspace_farmer_extra_package }}"
    state: present

- name: Download Subspace binary
  become: true
  ansible.builtin.get_url:
    url: "{{ subspace_farmer_binary_url }}"
    dest: "{{ subspace_farmer_binary_path }}"
    owner: "{{ subspace_farmer_user }}"
    group: "{{ subspace_farmer_group }}"
    force: true
    mode: '0750'
  notify:
    - subspace_farmer_need_restart

- name: Create subspace controller directory
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(subspace_farmer_user) }}"
    group: "{{ item.group | default(subspace_farmer_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ subspace_farmer_directories }}"

- name: Template Subspace Controller file
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(subspace_farmer_user) }}"
    group: "{{ item.group | default(subspace_farmer_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ subspace_farmer_templates }}"
  notify:
    - subspace_farmer_need_restart