---
nexus_user: nexus
nexus_group: nexus
nexus_groups: [certbot]

nexus_home: /opt/nexus
nexus_log_path: /var/log/nexus
nexus_ssl_path: "{{ nexus_home }}/ssl"
nexus_blob_path: "{{ nexus_home}}/sonatype-work/nexus3/blobs"

nexus_version: 3.68.0-04
nexus_java_version: 11
nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version}}-java{{ nexus_java_version }}-unix.tar.gz"

nexus_run_home: "{{ nexus_home}}/nexus-{{ nexus_version }}"
nexus_binary_path: "{{ nexus_run_home}}/bin/nexus"

nexus_package:
  - "openjdk-{{ nexus_java_version }}-jdk"



nexus_directories:
  - path: "{{ nexus_home }}"
  - path: "{{ nexus_ssl_path }}"
  - path: "{{ nexus_log_path }}"

nexus_templates:
  - src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

nexus_custom_become_method: sudo

nexus_vg_name: tartarus
nexus_filesystem_vgs_to_create:
  - vg: "{{ nexus_vg_name }}"

nexus_lv_name: lv_nexus
nexus_lv_size: 8g
nexus_log_size: 1g
nexus_log_lv_name: lv_nexus_log
nexus_filesystem_lvs_mounts:

  - lv: "{{ nexus_lv_name }}"
    vg: "{{ nexus_vg_name }}"
    size: "{{ nexus_lv_size }}"
    path: "{{ nexus_home }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"

  - lv: "{{ nexus_log_lv_name }}"
    vg: "{{ nexus_vg_name }}"
    size: "{{ nexus_log_size }}"
    path: "{{ nexus_log_path }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"

nexus_filesystem_disk_mounts:
  - disk: sdc
    path: "{{ nexus_blob_path }}/olympus"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"

  - disk: sdd
    path: "{{ nexus_blob_path }}/public"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"


nexus_ssl_enabled: true
nexus_ssl_file:
  - src: /opt/certbot/eden/cert.pem
    dest: "{{ nexus_ssl_path }}/cert.pem"
  - src: /opt/certbot/eden/chain.pem
    dest: "{{ nexus_ssl_path }}/chain.pem"
  - src: /opt/certbot/eden/fullchain.pem
    dest: "{{ nexus_ssl_path }}/fullchain.pem"
  - src: /opt/certbot/eden/fullchain.pem.key
    dest: "{{ nexus_ssl_path }}/fullchain.pem.key"
