---
nexus_owner: nexus
nexus_group: nexus

nexus_home: /opt/nexus
nexus_log_path: /var/log/nexus
nexus_ssl_path: "{{ nexus_home }}/ssl"
nexus_blob_path: "{{ nexus_home}}/sonatype-work/nexus3/blobs/"

nexus_version: 3.68.0-04
nexus_java_version: 11
nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version}}-java{{ nexus_java_version }}-unix.tar.gz"

nexus_binary_path: "/opt/nexus-{{ nexus_version }}/bin/nexus"

nexus_package:
  - "openjdk-{{ nexus_java_version }}-jdk"



nexus_directories:
  - path: "{{ nexus_home }}"
  - path: "{{ nexus_ssl_path }}"
  - path: "{{ nexus_log_path }}"

nexus_templates:
  - src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

nexus_custom_become_method: sudo

nexus_vg_name: olympus
nexus_log_size: 2g
nexus_log_lv_name: lv_nexus_log
nexus_filesystem_list:
  - disk: sdb
    path: "{{ nexus_blob_path }}/olympus"
    owner: "{{ nexus_owner }}"
    group: "{{ nexus_group }}"
    direct_mount: true
  - disk: sdc
    path: "{{ nexus_blob_path }}/public"
    owner: "{{ nexus_owner }}"
    group: "{{ nexus_group }}"
    direct_mount: true
  - lv: "{{ nexus_log_lv_name }}"
    vg: "{{ nexus_vg_name }}"
    size: "{{ nexus_log_size }}"
    path: "{{ nexus_log_path }}"
    owner: "{{ nexus_owner }}"
    group: "{{ nexus_group }}"

nexus_ssl_enabled: true
nexus_ssl_file:
  - src: /opt/certbot/eden/cert.pem
    dest: "{{ nexus_ssl_path }}/cert.pem"
  - src: /opt/certbot/eden/chain.pem
    dest: "{{ nexus_ssl_path }}/chain.pem"
  - src: /opt/certbot/eden/fullchain.pem
    dest: "{{ nexus_ssl_path }}/fullchain.pem"
  - src: /opt/certbot/eden/fullchain.pem.key
    dest: "{{ nexus_ssl_path }}/fullchain.pem.key"
